.gitignore, BTrees/_base.py, BTrees/tests/common.py, CHANGES.rst
When working on [zopefoundation/zc.zodbdgc#1](https://github.com/zopefoundation/zc.zodbdgc/pull/1#discussion-diff-27853357), we found a bug in the pure-Python BTree implementation. An `elif` that should have been its own `if` prevented the second and subsequent additions to a BTree from setting the `_p_changed` flag, right up until the first bucket needed to split. 
This can cause data-loss for small BTrees.
This PR adds a test case and should fix the issue (the comment is copied from the C implementation).
=> Fix setting _p_changed for small pure-Python BTrees.

BTrees/tests/common.py, BTrees/tests/testConflict.py
Prior to this PR, a large number of tests in the `w_zodb` environment would fail. Most of the errors came from `BTrees.tests.common:Base._closeRoot` trying to close a connection joined to a transaction. The remainder came from `BTrees.tests.testConflict` trying to use a non-MVCC-aware FileStorage from two different connections, leading to a "Duplicate tpc_begin calls for same transaction" error. This PR makes all tests in the `w_zodb` environment run (unfortunately that's not tested by Travis).
=> Make all the tests in the w_zodb Tox environment run.

BTrees/_base.py, BTrees/tests/common.py, CHANGES.rst
Sadly, the fix for #11 was incomplete (sorry) and failed to handle removal, which bit us testing our application under PyPy. This PR handles removal and adds test cases for it.
Example test failures before the fix:
```
======================================================================
FAIL: testRemoveInSmallMapSetsChanged (BTrees.tests.test_OOBTree.OOBTreePyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "//BTrees/BTrees/tests/common.py", line 1179, in testRemoveInSmallMapSetsChanged
self.assertTrue(t._p_changed)
AssertionError: False is not true
======================================================================
FAIL: testRemoveInSmallSetSetsChanged (BTrees.tests.test_OOBTree.OOTreeSetPyTest) …
```
=> Fix setting _p_changed when removing from small Python BTrees/TreeSets.

BTrees/_base.py, BTrees/tests/common.py, CHANGES.rst
This greatly assists debugging, and matches the C implementation.
It also makes doctests easier to run on both pure-Python and PyPy, e.g., zope.catalog.
=> Human-readable __repr__ for pure-Python Bucket and Set objects.

README.rst
The AppVeyor badge makes sense only after PR #30 is merged.
=> Add Travis and AppVeyor build badges

.travis.yml, appveyor.yml
There are some tests that are skipped if ZODB is not installed.
=> install zodb to make sure those dependent tests are run

.travis.yml
This adds python 3.4 on mac os x to the build matrix.
=> build BTrees for 3.4

doc-requirements.txt
This allows BTrees docs to build and be published on http://btrees.readthedocs.io. This is useful for intersphinx references. (The docs on pythonhosted.org/BTrees haven't been built since 2012 or so and don't have intersphinx data.)
=> Add requirements file for RTD.

README.rst
=> Point the doc link to the rendered site.

BTrees/BTreeTemplate.c, BTrees/BucketTemplate.c, BTrees/Development.txt, BTrees/objectkeymacros.h, BTrees/tests/test_OOBTree.py, CHANGES.rst, tox.ini
This makes the C implementation compatible with the Python implementation by only checking keys for default comparison when they are being set. (see #51)
It also makes it possible to delete unorderable keys, on Python 2 only. (see #53)
=> Check for object key default comparison on set only

BTrees/_base.py, BTrees/tests/test_OOBTree.py, CHANGES.rst
Check key identity before ==. This matches the C implementation.
Fixes #50
Add a pickle test to the work done in #54. Fixes #51. Fixes #53 (for
Python 2).
=> Python/C OO consistency

.manylinux-install.sh, .manylinux.sh, .travis.yml
Relates to #66 
This PR adds manylinux1 builds. Because, this builds bails out very quickly unless the instigating commit is a tagged commit. It should have minimal impact on zopefoundations' travis queue.
=> Build and deploy manylinux builds on tagged commit

.manylinux-install.sh
This whitespace prevented the 2.7 and 3.3 builds. attn @mgedmin
=> errant white space preventing some builds in manylinux

.travis.yml, BTrees/IFBTree.py, BTrees/IIBTree.py, BTrees/IOBTree.py, BTrees/LFBTree.py, BTrees/LLBTree.py, BTrees/LOBTree.py, BTrees/OIBTree.py, BTrees/OLBTree.py, BTrees/OOBTree.py, BTrees/_base.py, BTrees/_compat.py, BTrees/fsBTree.py, BTrees/tests/common.py, BTrees/tests/testBTrees.py, BTrees/tests/testBTreesUnicode.py, CHANGES.rst, appveyor.yml, setup.py, tox.ini
Add failing tests and then fix them. Use a common function to DRY in
all the modules.
Fixes #78
Also use zope.testrunner in tox (and travis) because it allows passing
arguments to select what tests to run, see slow tests, etc.
Simplify setup.py to always build the C modules and avoid polluting
wheel caches (the same as zope.security and other projects that have
been worked on lately).
Bump the minimum 'persistent' requirement to one that actually works
in PURE_PYTHON mode (plus fix wheel metadata; otherwise we need
environment markers).
Test PURE_PYTHON in environments on Travis. Do some minor tuning to
eliminate redundant test cases and speed up test time.
=> Support PURE_PYTHON at runtime. 

BTrees/_base.py, CHANGES.rst
Fixes #79
Slightly faster on CPython:
$ python -m perf timeit -s 'from struct import Struct; s = Struct("i"); unpack=s.unpack; pack=s.pack' 'unpack(pack(123456))'
.....................
Mean +- std dev: 252 ns +- 12 ns
$ python -m perf timeit -s 'from struct import Struct; s = Struct("i"); from operator import index; pack=s.pack' 'pack(index(123456))'
.....................
Mean +- std dev: 235 ns +- 6 ns
Very slightly faster on PyPy:
python -m perf timeit -s 'from struct import Struct; s = Struct("i"); unpack=s.unpack; pack=s.pack' 'unpack(pack(123456))'
.........
Mean +- std dev: 4.24 ns +- 0.12 ns
$ python -m perf timeit -s 'from struct import Struct; s = Struct("i"); from operator import index; pack=s.pack' 'pack(index(123456))'
.........
Mean +- std dev: 4.19 ns +- 0.10 ns
=> Use operator.index to avoid DeprecationWarning on Python 2

appveyor.yml
PowerShell interprets any stderr output from a child process as an
error.  This means warnings from pip about using
not-the-very-latest-version-how-dare-you and warnings from twine about
uploading the *.tar.gz which was probably already uploaded already and
might not be a bitwise identical copy because what even is
reproducibility cause the Appveyor builds to fail, even if the actual
binary wheels we want have been built and uploaded successfully.
*pauses to breathe*
=> Avoid spurious "failures" on Appveyor during releases

BTrees/tests/common.py, CHANGES.rst, setup.py
Stop being quite so strict in order to account for the differences between the C and Python implementations. But do test that we don't break the new features when we didn't already have a better form.
Fixes #94
Refs https://github.com/zopefoundation/persistent/issues/92
=> Fix tests against persistent 4.4.

BTrees/BucketTemplate.c, BTrees/tests/testBTreesUnicode.py, CHANGES.rst, tox.ini
Fixes #106.
The bug was in not checking the return value of PyUnicode_AsLatin1String() and passing a NULL to PyOS_snprintf().
The fix uses PyUnicode_FromFormat() and avoids all the hassle of manual encoding/sprintf/decoding and even calling repr().
I've also added a regression test and tweaked `tox.ini` to set PYTHONFAULTHANDLER=1 to make the segfault visible -- without that all you see is the test runner exiting unexpectedly with no additional output (and you have to interpret "exited with code -11" as _died from a SIGSEGV_ yourself).
=> Fix segfault on repr(OOBucket([... non-Latin-1 thingies ...]))

.manylinux.sh, .travis.yml
This PR makes it so we _always_ build manylinux wheels, but only upload them for git tags.  This is so we can notice problems like https://github.com/zopefoundation/persistent/issues/117#issuecomment-550260284 _before_ making releases, instead of after.
The diff is messy, for which I apologize.  I had to reformat the YAML to understand it.  Highlights:
- Moved regular Linux Python builds outside build matrix, for conciseness (unfortunately this means 3.6 builds are now done twice: once without WITH_COVERAGE and once with)
- Move twine upload from .manylinux.sh into .travis.yml's after_success, next to the twine upload used for Mac OS builds
- This means Travis can no longer do an 'exit 0' in before_install, so I had to override the install and script sections too
- Move 'docker pull' into …
=> Restructure Travis to always build manylinux wheels

.travis.yml
And update macOS python to 2.7.17 to try to fix uploads.
=> Build using newer manylinux image.

.travis.yml
Python 3.5 on Mac OS doesn't support TLS 1.2, which makes twine upload
fail, but we can use system Python 2.7 for twine upload, which works.
Also brings the rest of the Travis CI configuration closer in line to
the rest of the packages updated for
https://github.com/zopefoundation/meta/issues/11
=> Fix Python 3.5 MacOS wheel upload

.travis.yml
This should allow for making macos wheels for py3.8.
=> adds python 3.8 on macos to the travis build.

BTrees/_compat.h
Since https://github.com/zopefoundation/persistent/issues/125 this would result in compiler warnings.
No change note, this is an internal change.
Fixes #131
=> Python 3: Stop using undocumented PyLong_AS_LONG.

docs/overview.rst
Without this patch running `tox -e docs` would produce this:
```
Sphinx v2.4.4 en cours d'exécution
chargement de l'environnement pickled... fait
construction en cours [mo]:cibles pour les fichiers po 0 qui sont périmées
construction [doctest]:cibles pour les fichiers sources 4 qui sont périmées
mise-à-jour de l'environnement :0 ajouté, 0 modifié, 0 supprimé
recherche des fichiers périmés... aucun résultat
running tests...
Document: overview
------------------
**********************************************************************
File "overview.rst", line 412, in default
Failed example:
s = IISet(range(10))
Exception raised:
Traceback (most recent call last):
File "/usr/lib64/python3.7/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest default[1]>", line 1, in …
```
=> Fixed tox 'docs' environment

.travis.yml, BTrees/Interfaces.py, BTrees/tests/test_dynamic_btrees.py, CHANGES.rst, tox.ini
Fixes #137 
Requires a temporary switch to using unittest as the runner.
=> Ensure resolution order for all objects is consistent

BTrees/BTreeTemplate.c, BTrees/_base.py, BTrees/tests/common.py, BTrees/tests/test__base.py, CHANGES.rst
Hello up there. To test my module that computes diff for BTrees I was playing
with manually creating BTrees with different topologies[1,2] and hit the
following bug that was leading to segmentation faults:
C implementation of Tree.__setstate__ allows to pass in arbitrary objects in
place of children and casts child to (Bucket*) if child type is not type of the
tree
_without further checking that type of the child is actually Bucket_
This leads to crashes when later the code, that is accessing tree nodes,
goes to leafs, accesses passed in objects assuming they are buckets with
corresponding C-level Bucket structure layout, and oops dereferences e.g.
Bucket->keys, or Bucket->values from memory initialized via non-Bucket
C-level data.
-> Fix it by allowing to pass into tree.__setstate__ only …
=> Don't allow to pass bad child into tree.__setstate__ to avoid memory corruption and crash

BTrees/BTreeTemplate.c, BTrees/BucketTemplate.c, BTrees/Interfaces.py, BTrees/SetOpTemplate.c, BTrees/SetOpTemplate.h, BTrees/SetTemplate.c, BTrees/TreeSetTemplate.c, BTrees/_base.py, BTrees/tests/common.py, CHANGES.rst, tox.ini
Fixes #142 
Implementation of `__sub__`,  `__or__` and `__and__` as shortcuts for `difference`, `union` and `intersection`.
This makes the usage of BTrees datastructures closer to native python sets, that support those operators.
=> Shortcut operators for union, intersection and difference

BTrees/_base.py, BTrees/tests/common.py, BTrees/tests/testPersistency.py, CHANGES.rst, tox.ini
=> fix persistency bug in the Python version

CHANGES.rst, src/BTrees/Interfaces.py, src/BTrees/SetOpTemplate.c, src/BTrees/_base.py, src/BTrees/tests/common.py, src/BTrees/tests/test__base.py
The Python implementation already did this, so this only updates the C version to match.
For multiunion, all arguments can be arbitrary iterables. The others derive their return type from the first argument, so it must still be a BTree object, but the second can be anything. (And technically, this limitation only applies to the python version; the C version actually accepts anything for both arguments, except for `difference` which also has the same limitation. I wasn't motivated to fix the Python version to accept arbitrary items in the first argument. But I will open a bug report if this gets merged.)
Fixes #24
=> Make multiunion(), union(), difference(), and intersection() work with arbitrary iterables

CHANGES.rst, src/BTrees/BTreeModuleTemplate.c, src/BTrees/BTreeTemplate.c, src/BTrees/BucketTemplate.c, src/BTrees/tests/common.py
=> Fix methods get, pop, setdefault and __contains__ to not hide POSKeyError

CHANGES.rst, src/BTrees/BTreeTemplate.c, src/BTrees/BucketTemplate.c, src/BTrees/Interfaces.py, src/BTrees/SetTemplate.c, src/BTrees/TreeSetTemplate.c, src/BTrees/_base.py, src/BTrees/_compat.h, src/BTrees/_compat.py, src/BTrees/_module_builder.py, src/BTrees/tests/common.py
Add tests to verify they implement the required methods. Turns out they didn't, so implement them.
This means `popitem` for the mappings, and `pop/discard/isdisjoint` plus a swath of operators for the sets.
Do this in both C and Python. The implementations are probably on the naive side, in that they work with generic iterators and don't try to do any complex structural merging, but that makes them easier to understand and hopefully be correct. Performance shouldn't be too bad, nothing worse than `O(N*logM)` (roughly). The `__iand__` method requires extra storage space of up to `O(N)`, and `__xor__` requires storage of O(N*M).
Fixes #121
This was a lot bigger than I expected.
=> Register BTree/Bucket as MutableMapping and Set/TreeSet as MutableSet, add missing methods/operators

CHANGES.rst, src/BTrees/SetTemplate.c, src/BTrees/TreeSetTemplate.c, src/BTrees/_datatypes.py, src/BTrees/objectkeymacros.h, src/BTrees/tests/common.py, src/BTrees/tests/test_OOBTree.py
Fixes #153.
Also take the opportunity to clean up the TODOs in _datatypes.py with regards to checking for default comparison: Use a metaclass so we get caching, and only check for the special methods on the type object.
=> Python 2: Forbid type objects as keys.

CHANGES.rst, src/BTrees/BTreeTemplate.c, src/BTrees/tests/common.py
This was broken by #166.
Fixes #168. Instead of directly raising the TypeError ourself for an unknown attribute, defer to `PyType_Type.tp_setatro` if we don't know the attribute.
This was a surprise breakage. I'd be grateful if anyone can review this quickly.
=> Fix setting class attributes on BTree subclasses.

CHANGES.rst, src/BTrees/SetOpTemplate.c, src/BTrees/_base.py, src/BTrees/tests/common.py
Fixes #171.
Currently based on #172; only the last commit is relevant here.
=> Make the set operation functions automatically sort a copy of an arbitrary iterable.

.github/workflows/tests.yml, .meta.toml, CHANGES.rst, MANIFEST.in, include/persistent/persistent/_compat.h, include/persistent/persistent/cPersistence.h, include/persistent/persistent/ring.h, setup.py
Analogous to https://github.com/zopefoundation/zope.security/pull/98 this PR prevents wheel building issues on macOS with Python `universal2` architecture
=> Drop using ``setup_requires`` due to constant problems on GHA

.github/workflows/tests.yml, .manylinux-install.sh, .meta.toml, CHANGES.rst, appveyor.yml, tox.ini
=> Preliminary support for Python 3.13a3

.github/workflows/tests.yml, .manylinux-install.sh, .meta.toml, appveyor.yml, setup.cfg, tox.ini
This is needed to make tests on `master` green again, until we found a solution for #197
=> Remove preliminary support for Python 3.13 as it is not yet ready.
